[tools]
node = "lts"
go = "latest"
rust = "latest"
python = "latest"
lsd = "latest"
bat = "latest"
ripgrep = "latest"
delta = "latest"
fzf = "latest"
oh-my-posh = "latest"
usage = "latest"
btop = "latest"
